<?php

namespace App\Filament\Resources;

use App\Filament\Resources\BusinessProfileResource\Pages;
use App\Filament\Resources\BusinessProfileResource\RelationManagers;
use App\Models\BusinessProfile;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class BusinessProfileResource extends Resource
{
    protected static ?string $model = BusinessProfile::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('user_id')
                    ->required()
                    ->numeric(),
                Forms\Components\Toggle::make('onboarding_completed')
                    ->required(),
                Forms\Components\TextInput::make('onboarding_step')
                    ->numeric(),
                Forms\Components\DateTimePicker::make('onboarding_completed_at'),
                Forms\Components\TextInput::make('business_name')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('business_type')
                    ->required(),
                Forms\Components\TextInput::make('industry'),
                Forms\Components\TextInput::make('business_address')
                    ->maxLength(191),
                Forms\Components\TextInput::make('business_city')
                    ->maxLength(191),
                Forms\Components\TextInput::make('business_state')
                    ->maxLength(191),
                Forms\Components\TextInput::make('business_country')
                    ->maxLength(191),
                Forms\Components\TextInput::make('business_phone')
                    ->tel()
                    ->maxLength(191),
                Forms\Components\Textarea::make('ein_tax_id')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('rating_average')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('total_reviews')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('communication_rating')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('punctuality_rating')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('professionalism_rating')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('total_shifts_posted')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_shifts_completed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_shifts_cancelled')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('average_shift_cost')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('total_spent')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('pending_payment')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('unique_workers_hired')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('repeat_workers')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('subscription_plan')
                    ->required(),
                Forms\Components\DateTimePicker::make('subscription_expires_at'),
                Forms\Components\TextInput::make('monthly_credit_limit')
                    ->numeric(),
                Forms\Components\TextInput::make('monthly_credit_used')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('fill_rate')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('cancellation_rate')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('late_cancellations')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_cancellation_penalties')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('open_support_tickets')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\DateTimePicker::make('last_support_contact'),
                Forms\Components\Toggle::make('priority_support')
                    ->required(),
                Forms\Components\Toggle::make('account_in_good_standing')
                    ->required(),
                Forms\Components\Textarea::make('account_warning_message')
                    ->columnSpanFull(),
                Forms\Components\DateTimePicker::make('last_shift_posted_at'),
                Forms\Components\Toggle::make('can_post_shifts')
                    ->required(),
                Forms\Components\Toggle::make('is_verified')
                    ->required(),
                Forms\Components\TextInput::make('verification_status')
                    ->required()
                    ->maxLength(191)
                    ->default('pending'),
                Forms\Components\Textarea::make('verification_notes')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('business_license_url')
                    ->maxLength(191),
                Forms\Components\TextInput::make('insurance_certificate_url')
                    ->maxLength(191),
                Forms\Components\TextInput::make('tax_document_url')
                    ->maxLength(191),
                Forms\Components\DateTimePicker::make('documents_submitted_at'),
                Forms\Components\DateTimePicker::make('verified_at'),
                Forms\Components\TextInput::make('business_registration_number')
                    ->maxLength(191),
                Forms\Components\TextInput::make('phone')
                    ->tel()
                    ->maxLength(191),
                Forms\Components\TextInput::make('website')
                    ->maxLength(191),
                Forms\Components\TextInput::make('address')
                    ->maxLength(191),
                Forms\Components\TextInput::make('city')
                    ->maxLength(100),
                Forms\Components\TextInput::make('state')
                    ->maxLength(100),
                Forms\Components\TextInput::make('zip_code')
                    ->maxLength(20),
                Forms\Components\TextInput::make('country')
                    ->maxLength(100),
                Forms\Components\Textarea::make('description')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('total_locations')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\Toggle::make('multi_location_enabled')
                    ->required(),
                Forms\Components\TextInput::make('active_venues')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_templates')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('active_templates')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('employee_count')
                    ->maxLength(191),
                Forms\Components\TextInput::make('rating')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\Toggle::make('has_payment_method')
                    ->required(),
                Forms\Components\Toggle::make('autopay_enabled')
                    ->required(),
                Forms\Components\TextInput::make('default_payment_method_id')
                    ->maxLength(191),
                Forms\Components\TextInput::make('preferred_worker_ids'),
                Forms\Components\TextInput::make('blacklisted_worker_ids'),
                Forms\Components\Toggle::make('allow_new_workers')
                    ->required(),
                Forms\Components\TextInput::make('minimum_worker_rating')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('minimum_shifts_completed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Toggle::make('is_complete')
                    ->required(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('user_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('onboarding_completed')
                    ->boolean(),
                Tables\Columns\TextColumn::make('onboarding_step')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('onboarding_completed_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('business_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('business_type'),
                Tables\Columns\TextColumn::make('industry'),
                Tables\Columns\TextColumn::make('business_address')
                    ->searchable(),
                Tables\Columns\TextColumn::make('business_city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('business_state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('business_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('business_phone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('rating_average')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_reviews')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('communication_rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('punctuality_rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('professionalism_rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_shifts_posted')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_shifts_completed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_shifts_cancelled')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('average_shift_cost')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_spent')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('pending_payment')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('unique_workers_hired')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('repeat_workers')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('subscription_plan'),
                Tables\Columns\TextColumn::make('subscription_expires_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('monthly_credit_limit')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('monthly_credit_used')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('fill_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('cancellation_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('late_cancellations')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_cancellation_penalties')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('open_support_tickets')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('last_support_contact')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\IconColumn::make('priority_support')
                    ->boolean(),
                Tables\Columns\IconColumn::make('account_in_good_standing')
                    ->boolean(),
                Tables\Columns\TextColumn::make('last_shift_posted_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\IconColumn::make('can_post_shifts')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_verified')
                    ->boolean(),
                Tables\Columns\TextColumn::make('verification_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('business_license_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('insurance_certificate_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tax_document_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('documents_submitted_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('verified_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('business_registration_number')
                    ->searchable(),
                Tables\Columns\TextColumn::make('phone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('website')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address')
                    ->searchable(),
                Tables\Columns\TextColumn::make('city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('zip_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('total_locations')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('multi_location_enabled')
                    ->boolean(),
                Tables\Columns\TextColumn::make('active_venues')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_templates')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('active_templates')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('employee_count')
                    ->searchable(),
                Tables\Columns\TextColumn::make('rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('has_payment_method')
                    ->boolean(),
                Tables\Columns\IconColumn::make('autopay_enabled')
                    ->boolean(),
                Tables\Columns\TextColumn::make('default_payment_method_id')
                    ->searchable(),
                Tables\Columns\IconColumn::make('allow_new_workers')
                    ->boolean(),
                Tables\Columns\TextColumn::make('minimum_worker_rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('minimum_shifts_completed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_complete')
                    ->boolean(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListBusinessProfiles::route('/'),
            'create' => Pages\CreateBusinessProfile::route('/create'),
            'edit' => Pages\EditBusinessProfile::route('/{record}/edit'),
        ];
    }
}
