<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ShiftResource\Pages;
use App\Filament\Resources\ShiftResource\RelationManagers;
use App\Models\Shift;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ShiftResource extends Resource
{
    protected static ?string $model = Shift::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('business_id')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('agency_client_id')
                    ->numeric(),
                Forms\Components\TextInput::make('posted_by_agency_id')
                    ->numeric(),
                Forms\Components\TextInput::make('venue_id')
                    ->numeric(),
                Forms\Components\TextInput::make('title')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('role_type')
                    ->maxLength(191),
                Forms\Components\Textarea::make('description')
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('industry')
                    ->required(),
                Forms\Components\TextInput::make('location_address')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('location_city')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('location_state')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('location_country')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('location_lat')
                    ->numeric(),
                Forms\Components\TextInput::make('location_lng')
                    ->numeric(),
                Forms\Components\TextInput::make('geofence_radius')
                    ->required()
                    ->numeric()
                    ->default(100),
                Forms\Components\TextInput::make('early_clockin_minutes')
                    ->required()
                    ->numeric()
                    ->default(15),
                Forms\Components\TextInput::make('late_grace_minutes')
                    ->required()
                    ->numeric()
                    ->default(10),
                Forms\Components\DatePicker::make('shift_date')
                    ->required(),
                Forms\Components\TextInput::make('start_time')
                    ->required(),
                Forms\Components\TextInput::make('end_time')
                    ->required(),
                Forms\Components\TextInput::make('duration_hours')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('minimum_shift_duration')
                    ->required()
                    ->numeric()
                    ->default(3.00),
                Forms\Components\TextInput::make('maximum_shift_duration')
                    ->required()
                    ->numeric()
                    ->default(12.00),
                Forms\Components\TextInput::make('required_rest_hours')
                    ->required()
                    ->numeric()
                    ->default(8.00),
                Forms\Components\TextInput::make('base_rate')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('minimum_wage')
                    ->numeric(),
                Forms\Components\TextInput::make('dynamic_rate')
                    ->numeric(),
                Forms\Components\TextInput::make('final_rate')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('base_worker_pay')
                    ->numeric(),
                Forms\Components\TextInput::make('platform_fee_rate')
                    ->required()
                    ->numeric()
                    ->default(35.00),
                Forms\Components\TextInput::make('platform_fee_amount')
                    ->numeric(),
                Forms\Components\TextInput::make('vat_rate')
                    ->required()
                    ->numeric()
                    ->default(18.00),
                Forms\Components\TextInput::make('vat_amount')
                    ->numeric(),
                Forms\Components\TextInput::make('total_business_cost')
                    ->numeric(),
                Forms\Components\TextInput::make('escrow_amount')
                    ->numeric(),
                Forms\Components\TextInput::make('contingency_buffer_rate')
                    ->required()
                    ->numeric()
                    ->default(5.00),
                Forms\Components\TextInput::make('urgency_level')
                    ->required(),
                Forms\Components\TextInput::make('surge_multiplier')
                    ->required()
                    ->numeric()
                    ->default(1.00),
                Forms\Components\TextInput::make('time_surge')
                    ->required()
                    ->numeric()
                    ->default(1.00),
                Forms\Components\TextInput::make('demand_surge')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('event_surge')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\Toggle::make('is_public_holiday')
                    ->required(),
                Forms\Components\Toggle::make('is_night_shift')
                    ->required(),
                Forms\Components\Toggle::make('is_weekend')
                    ->required(),
                Forms\Components\TextInput::make('status')
                    ->required(),
                Forms\Components\Toggle::make('in_market')
                    ->required(),
                Forms\Components\Toggle::make('is_demo')
                    ->required(),
                Forms\Components\Toggle::make('instant_claim_enabled')
                    ->required(),
                Forms\Components\TextInput::make('demo_business_name')
                    ->maxLength(191),
                Forms\Components\TextInput::make('market_views')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('market_applications')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\DateTimePicker::make('market_posted_at'),
                Forms\Components\Toggle::make('requires_overtime_approval')
                    ->required(),
                Forms\Components\Toggle::make('has_disputes')
                    ->required(),
                Forms\Components\Toggle::make('auto_approval_eligible')
                    ->required(),
                Forms\Components\DateTimePicker::make('confirmed_at'),
                Forms\Components\DateTimePicker::make('priority_notification_sent_at'),
                Forms\Components\DateTimePicker::make('started_at'),
                Forms\Components\DateTimePicker::make('first_worker_clocked_in_at'),
                Forms\Components\DateTimePicker::make('completed_at'),
                Forms\Components\DateTimePicker::make('last_worker_clocked_out_at'),
                Forms\Components\DateTimePicker::make('verified_at'),
                Forms\Components\TextInput::make('verified_by')
                    ->numeric(),
                Forms\Components\DateTimePicker::make('auto_approved_at'),
                Forms\Components\TextInput::make('cancelled_by')
                    ->numeric(),
                Forms\Components\DateTimePicker::make('cancelled_at'),
                Forms\Components\Textarea::make('cancellation_reason')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('cancellation_type'),
                Forms\Components\TextInput::make('cancellation_penalty_amount')
                    ->numeric(),
                Forms\Components\TextInput::make('worker_compensation_amount')
                    ->numeric(),
                Forms\Components\TextInput::make('required_workers')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\TextInput::make('filled_workers')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('application_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('view_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\DateTimePicker::make('first_application_at'),
                Forms\Components\DateTimePicker::make('last_application_at'),
                Forms\Components\TextInput::make('requirements'),
                Forms\Components\TextInput::make('required_skills'),
                Forms\Components\TextInput::make('required_certifications'),
                Forms\Components\TextInput::make('dress_code')
                    ->maxLength(191),
                Forms\Components\TextInput::make('parking_info')
                    ->maxLength(191),
                Forms\Components\TextInput::make('break_info')
                    ->maxLength(191),
                Forms\Components\Textarea::make('special_instructions')
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('posted_by_agent')
                    ->required(),
                Forms\Components\Toggle::make('allow_agencies')
                    ->required(),
                Forms\Components\TextInput::make('agent_id')
                    ->numeric(),
                Forms\Components\TextInput::make('template_id')
                    ->numeric(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('business_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('agency_client_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('posted_by_agency_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('venue_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('title')
                    ->searchable(),
                Tables\Columns\TextColumn::make('role_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('industry'),
                Tables\Columns\TextColumn::make('location_address')
                    ->searchable(),
                Tables\Columns\TextColumn::make('location_city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('location_state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('location_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('location_lat')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('location_lng')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('geofence_radius')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('early_clockin_minutes')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('late_grace_minutes')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('shift_date')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('start_time'),
                Tables\Columns\TextColumn::make('end_time'),
                Tables\Columns\TextColumn::make('duration_hours')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('minimum_shift_duration')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('maximum_shift_duration')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('required_rest_hours')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('base_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('minimum_wage')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('dynamic_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('final_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('base_worker_pay')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('platform_fee_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('platform_fee_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('vat_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('vat_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_business_cost')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('escrow_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('contingency_buffer_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('urgency_level'),
                Tables\Columns\TextColumn::make('surge_multiplier')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('time_surge')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('demand_surge')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('event_surge')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_public_holiday')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_night_shift')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_weekend')
                    ->boolean(),
                Tables\Columns\TextColumn::make('status'),
                Tables\Columns\IconColumn::make('in_market')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_demo')
                    ->boolean(),
                Tables\Columns\IconColumn::make('instant_claim_enabled')
                    ->boolean(),
                Tables\Columns\TextColumn::make('demo_business_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('market_views')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('market_applications')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('market_posted_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\IconColumn::make('requires_overtime_approval')
                    ->boolean(),
                Tables\Columns\IconColumn::make('has_disputes')
                    ->boolean(),
                Tables\Columns\IconColumn::make('auto_approval_eligible')
                    ->boolean(),
                Tables\Columns\TextColumn::make('confirmed_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('priority_notification_sent_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('started_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('first_worker_clocked_in_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('completed_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('last_worker_clocked_out_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('verified_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('verified_by')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('auto_approved_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('cancelled_by')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('cancelled_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('cancellation_type'),
                Tables\Columns\TextColumn::make('cancellation_penalty_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('worker_compensation_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('required_workers')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('filled_workers')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('application_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('view_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('first_application_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('last_application_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('dress_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parking_info')
                    ->searchable(),
                Tables\Columns\TextColumn::make('break_info')
                    ->searchable(),
                Tables\Columns\IconColumn::make('posted_by_agent')
                    ->boolean(),
                Tables\Columns\IconColumn::make('allow_agencies')
                    ->boolean(),
                Tables\Columns\TextColumn::make('agent_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('template_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListShifts::route('/'),
            'create' => Pages\CreateShift::route('/create'),
            'edit' => Pages\EditShift::route('/{record}/edit'),
        ];
    }
}
