<?php

namespace App\Filament\Resources;

use App\Filament\Resources\WorkerProfileResource\Pages;
use App\Filament\Resources\WorkerProfileResource\RelationManagers;
use App\Models\WorkerProfile;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class WorkerProfileResource extends Resource
{
    protected static ?string $model = WorkerProfile::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('user_id')
                    ->required()
                    ->numeric(),
                Forms\Components\Toggle::make('onboarding_completed')
                    ->required(),
                Forms\Components\TextInput::make('onboarding_step')
                    ->numeric(),
                Forms\Components\DateTimePicker::make('onboarding_completed_at'),
                Forms\Components\Toggle::make('identity_verified')
                    ->required(),
                Forms\Components\DateTimePicker::make('identity_verified_at'),
                Forms\Components\TextInput::make('identity_verification_method')
                    ->maxLength(191),
                Forms\Components\TextInput::make('subscription_tier')
                    ->required(),
                Forms\Components\DateTimePicker::make('tier_expires_at'),
                Forms\Components\DateTimePicker::make('tier_upgraded_at'),
                Forms\Components\Textarea::make('bio')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('hourly_rate_min')
                    ->numeric(),
                Forms\Components\TextInput::make('hourly_rate_max')
                    ->numeric(),
                Forms\Components\TextInput::make('industries'),
                Forms\Components\TextInput::make('preferred_industries'),
                Forms\Components\TextInput::make('profile_photo_url')
                    ->maxLength(191),
                Forms\Components\TextInput::make('resume_url')
                    ->maxLength(191),
                Forms\Components\TextInput::make('linkedin_url')
                    ->maxLength(191),
                Forms\Components\TextInput::make('availability_schedule'),
                Forms\Components\TextInput::make('transportation')
                    ->required(),
                Forms\Components\TextInput::make('max_commute_distance')
                    ->required()
                    ->numeric()
                    ->default(10),
                Forms\Components\TextInput::make('years_experience')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('rating_average')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('total_shifts_completed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('reliability_score')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('total_no_shows')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_cancellations')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_late_arrivals')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_early_departures')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_no_acknowledgments')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('average_response_time_minutes')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_earnings')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('pending_earnings')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('withdrawn_earnings')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('average_hourly_earned')
                    ->numeric(),
                Forms\Components\TextInput::make('referral_code')
                    ->maxLength(20),
                Forms\Components\TextInput::make('referred_by')
                    ->maxLength(20),
                Forms\Components\TextInput::make('total_referrals')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('referral_earnings')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('location_city')
                    ->maxLength(191),
                Forms\Components\TextInput::make('location_state')
                    ->maxLength(191),
                Forms\Components\TextInput::make('location_country')
                    ->maxLength(191),
                Forms\Components\TextInput::make('background_check_status')
                    ->required(),
                Forms\Components\DatePicker::make('background_check_date'),
                Forms\Components\Textarea::make('background_check_notes')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('phone')
                    ->tel()
                    ->maxLength(191),
                Forms\Components\DatePicker::make('date_of_birth'),
                Forms\Components\TextInput::make('address')
                    ->maxLength(191),
                Forms\Components\TextInput::make('city')
                    ->maxLength(100),
                Forms\Components\TextInput::make('state')
                    ->maxLength(100),
                Forms\Components\TextInput::make('zip_code')
                    ->maxLength(20),
                Forms\Components\TextInput::make('country')
                    ->maxLength(100),
                Forms\Components\TextInput::make('emergency_contact_name')
                    ->maxLength(191),
                Forms\Components\TextInput::make('emergency_contact_phone')
                    ->tel()
                    ->maxLength(191),
                Forms\Components\TextInput::make('skills'),
                Forms\Components\TextInput::make('certifications'),
                Forms\Components\TextInput::make('hourly_rate')
                    ->numeric(),
                Forms\Components\TextInput::make('rating')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('completed_shifts')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Toggle::make('is_available')
                    ->required(),
                Forms\Components\Toggle::make('is_complete')
                    ->required(),
                Forms\Components\TextInput::make('location_lat')
                    ->numeric(),
                Forms\Components\TextInput::make('location_lng')
                    ->numeric(),
                Forms\Components\TextInput::make('preferred_radius')
                    ->required()
                    ->numeric()
                    ->default(25),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('user_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('onboarding_completed')
                    ->boolean(),
                Tables\Columns\TextColumn::make('onboarding_step')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('onboarding_completed_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\IconColumn::make('identity_verified')
                    ->boolean(),
                Tables\Columns\TextColumn::make('identity_verified_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('identity_verification_method')
                    ->searchable(),
                Tables\Columns\TextColumn::make('subscription_tier'),
                Tables\Columns\TextColumn::make('tier_expires_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('tier_upgraded_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('hourly_rate_min')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('hourly_rate_max')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('profile_photo_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('resume_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('linkedin_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('transportation'),
                Tables\Columns\TextColumn::make('max_commute_distance')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('years_experience')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('rating_average')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_shifts_completed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('reliability_score')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_no_shows')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_cancellations')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_late_arrivals')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_early_departures')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_no_acknowledgments')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('average_response_time_minutes')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_earnings')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('pending_earnings')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('withdrawn_earnings')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('average_hourly_earned')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('referral_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('referred_by')
                    ->searchable(),
                Tables\Columns\TextColumn::make('total_referrals')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('referral_earnings')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('location_city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('location_state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('location_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('background_check_status'),
                Tables\Columns\TextColumn::make('background_check_date')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('phone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('date_of_birth')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('address')
                    ->searchable(),
                Tables\Columns\TextColumn::make('city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('zip_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('emergency_contact_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('emergency_contact_phone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('hourly_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('completed_shifts')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_available')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_complete')
                    ->boolean(),
                Tables\Columns\TextColumn::make('location_lat')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('location_lng')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('preferred_radius')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListWorkerProfiles::route('/'),
            'create' => Pages\CreateWorkerProfile::route('/create'),
            'edit' => Pages\EditWorkerProfile::route('/{record}/edit'),
        ];
    }
}
